services:
  - type: web
    name: toxiguard-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: toxiguard-db
          property: connectionString
      - key: USE_EXTERNAL_APIS
        value: False  # 最初はFalseで起動テスト
      - key: ENABLE_TOXIC_BERT
        value: False
      - key: LOG_LEVEL
        value: INFO
      - key: DEV_MODE
        value: True
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: toxiguard-db
    databaseName: toxiguard_db
    user: toxiguard
    plan: free