"""Initial migration with feedback tables

Revision ID: f5120bd53e3a
Revises: 
Create Date: 2025-06-13 13:58:14.658337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5120bd53e3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=True),
    sa.Column('original_score', sa.Float(), nullable=False),
    sa.Column('original_is_toxic', sa.Boolean(), nullable=False),
    sa.Column('original_categories', sa.JSON(), nullable=True),
    sa.Column('original_confidence', sa.Float(), nullable=True),
    sa.Column('user_is_toxic', sa.Boolean(), nullable=False),
    sa.Column('user_category', sa.String(length=50), nullable=True),
    sa.Column('user_severity', sa.Float(), nullable=True),
    sa.Column('feedback_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    op.create_table('model_performances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('total_feedbacks', sa.Integer(), nullable=True),
    sa.Column('correct_predictions', sa.Integer(), nullable=True),
    sa.Column('false_positives', sa.Integer(), nullable=True),
    sa.Column('false_negatives', sa.Integer(), nullable=True),
    sa.Column('category_performance', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_performances_id'), 'model_performances', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_performances_id'), table_name='model_performances')
    op.drop_table('model_performances')
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
